repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.1
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: pytest-pre-push
      name: Run Pytest on Pre-Push
      entry: .venv/bin/pytest
      language: system
      always_run: true
      pass_filenames: false
      types: [python]
      stages: [pre-push]

